title = "Workload example"

[global]
    Duration = "160s"
    server="127.0.0.1"
    port="8081"
    TLSMode=false
    [global.StatusCodesAcceptance]
        200 = 100.0 # upto 100% return status of 200
        204 = 100.0
        205 = 100.0

[workloads]
    [workloads.load_to_t1]
        name="load_to_t1"
        Generator="csv2kv_perf"
        container="bigdata"
        Target="mytable/"
        workers=10
        duration="60s"
        payload="examples/payloads/order-book-sample.csv"
        schema="examples/schemas/schema_example.json"
	[workloads.load_to_t1.header]
          X-v3io-session-key="a90a2aa8-663a-497d-98d0-47f260080615"
          X-v3io-function="PutItem"

